[build]
command = 'hugo'
publish = 'public'
[build.environment]
HUGO_VERSION = '0.90.1'


[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_VERSION = '0.90.1'
HUGO_ENV = 'production'

[context.branch-deploy.environment]
  HUGO_VERSION = "0.90.1" # if older, use format: 0.53 (no trailing zero)

[context.deploy-preview.environment]
  HUGO_VERSION = "0.90.1"

